const PEOPLE=["Anouk","Leon","Daniela","Marc"],TARGET=510,WEEK=2550,$=s=>document.querySelector(s);
let person=localStorage.getItem("zg_person"), data={}, db=null, unsub=null;
const pad=n=>String(n).padStart(2,"0"), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, fmt=m=>`${Math.floor(Math.max(0,m)/60)}:${pad(Math.round(Math.max(0,m))%60)}`;
const delta=m=>(m>0?"+ ":m<0?"− ":"± ")+fmt(Math.abs(m)), mon=d=>{let x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}, add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
function ensure(ds){data[ds]??={entries:[],running:null};return data[ds]}
function mins(ds,now=new Date()){let d=data[ds],t=0;if(!d)return 0;for(const e of d.entries||[])t+=(new Date(e.end)-new Date(e.start))/60000;if(d.running)t+=(now-new Date(d.running))/60000;return t}
function target(d){return [0,6].includes(d.getDay())?0:TARGET}
async function initFB(){const cfg=window.TIMEAPP_FIREBASE_CONFIG;if(!cfg)return;const {initializeApp}=await import("https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js");const {getFirestore,doc,setDoc,onSnapshot}=await import("https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js");db=getFirestore(initializeApp(cfg));window.F={doc,setDoc,onSnapshot}}
function subscribe(){if(unsub)unsub();if(!person)return;const ref=F.doc(db,"timeappUsers",person);unsub=F.onSnapshot(ref,s=>{data=s.exists()?(s.data().days||{}):{};render()})}
async function save(){await F.setDoc(F.doc(db,"timeappUsers",person),{days:data,updatedAt:new Date().toISOString()},{merge:true})}
function render(){if(!person){$("#sheet").classList.remove("hidden");return}$("#personBtn").textContent=person;let now=new Date(),ds=iso(now),m=mins(ds,now),tar=target(now),dd=m-tar;$("#date").textContent=now.toLocaleDateString("de-CH",{weekday:"long",day:"numeric",month:"long"});$("#today").textContent=fmt(m);$("#delta").textContent=delta(dd);$("#delta").className=tar?(dd>=0?"good":"bad"):(m>0?"good":"");$("#target").textContent=tar?`Soll ${fmt(tar)}`:"Kein Soll";$("#fill").style.width=tar?Math.min(100,m/tar*100)+"%":(m?"100%":"0%");let run=!!data[ds]?.running;$("#status").textContent=run?"Arbeitszeit läuft …":"Nicht am Arbeiten";$("#toggle").textContent=run?"■ Stopp":"▶ Start";
let mo=mon(now),we=0,box=$("#days");box.innerHTML="";for(let i=0;i<7;i++){let d=add(mo,i),s=iso(d),x=mins(s,now),t=target(d),z=x-t;we+=x;let r=document.createElement("div");r.className="day";r.innerHTML=`<div><b>${d.toLocaleDateString("de-CH",{weekday:"short"})}</b><div>${d.toLocaleDateString("de-CH",{day:"2-digit",month:"2-digit"})}</div></div><div>${t?`Soll ${fmt(t)}`:"ohne Soll"}</div><div><strong>${fmt(x)}</strong><div class="${t?(z>=0?"good":"bad"):(x?"good":"")}">${t?delta(z):(x?"+ "+fmt(x):"± 0:00")}</div></div>`;box.appendChild(r)}
$("#week").textContent=fmt(we);let wd=we-WEEK;$("#weekDelta").textContent=`Soll 42:30 · ${delta(wd)}`;$("#weekDelta").className=wd>=0?"good":"bad";$("#avg").textContent=fmt(we/5);$("#range").textContent=`${mo.toLocaleDateString("de-CH",{day:"2-digit",month:"2-digit"})} – ${add(mo,6).toLocaleDateString("de-CH",{day:"2-digit",month:"2-digit",year:"numeric"})}`}
$("#toggle").onclick=async()=>{let now=new Date(),ds=iso(now),d=ensure(ds);if(d.running){d.entries.push({start:d.running,end:now.toISOString()});d.running=null}else d.running=now.toISOString();await save();render()}
$("#personBtn").onclick=()=>$("#sheet").classList.remove("hidden");PEOPLE.forEach(p=>{let b=document.createElement("button");b.className="person";b.textContent=p;b.onclick=()=>{person=p;localStorage.setItem("zg_person",p);$("#sheet").classList.add("hidden");subscribe()};$("#people").appendChild(b)});
$("#manual").onclick=()=>{$("#mDate").value=iso(new Date());$("#mStart").value="08:00";$("#mEnd").value="17:00";$("#manualSheet").classList.remove("hidden")};$("#cancel").onclick=()=>$("#manualSheet").classList.add("hidden");$("#saveManual").onclick=async()=>{let ds=$("#mDate").value,s=$("#mStart").value,e=$("#mEnd").value,a=new Date(`${ds}T${s}`),b=new Date(`${ds}T${e}`);if(b<=a)return alert("Endzeit muss nach Startzeit liegen.");ensure(ds).entries.push({start:a.toISOString(),end:b.toISOString()});await save();$("#manualSheet").classList.add("hidden");render()};
await initFB(); if(person)subscribe(); else render(); setInterval(render,1000); if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");